### ISSUE TITLE
ValueError: Unknown information requested: ['expert_plan', 'expert_type']

### ISSUE THREAD

**Issue by im-renpei** [archiki/ADaPT#5]
```
(adapt-alfworld-env) ➜  ADaPT git:(main) ✗ python run_alfworld.py           
Initializing AlfredTWEnv...
Checking for solvable games...
Overall we have 134 games
Evaluating with 134 games
Traceback (most recent call last):
  File "/home/pren/Devs/ADaPT_ws/ADaPT/run_alfworld.py", line 202, in <module>
    env = orig_env.init_game(batch_size=1, game_file=game_files[2])
  File "/home/pren/Devs/ADaPT_ws/alfworld/alfworld/agents/environment/alfred_tw_env.py", line 251, in init_game
    infos = textworld.EnvInfos(won=True, admissible_commands=True, expert_type=expert_type, expert_plan=expert_plan, extras=["gamefile"])
  File "/home/pren/anaconda3/envs/adapt-alfworld-env/lib/python3.9/site-packages/textworld/core.py", line 109, in __init__
    raise ValueError(msg)
ValueError: Unknown information requested: ['expert_plan', 'expert_type']. Available information are: ['admissible_commands', 'command_templates', 'description', 'entities', 'extras', 'facts', 'fail_facts', 'feedback', 'game', 'intermediate_reward', 'inventory', 'last_action', 'last_command', 'location', 'lost', 'max_score', 'moves', 'objective', 'policy_commands', 'score', 'verbs', 'win_facts', 'won']
(adapt-alfworld-env) ➜  ADaPT git:(main) ✗
```

**Comment by archiki** [comment]
Thanks for pointing this out, at the time of developing ADaPT we used version [alfworld v0.2.2](https://arxiv.org/pdf/2402.10963.pdf) which has been updated since. Reverting to the older version should resolve this error.

**Comment by WZX0Swarm0Robotics** [comment]
> Thanks for pointing this out, at the time of developing ADaPT we used version [alfworld v0.2.2](https://arxiv.org/pdf/2402.10963.pdf) which has been updated since. Reverting to the older version should resolve this error.

I also encountered this problem. I have changed the version of alfworld to 0.2.2, but it still doesn’t work and continues to return this error.
